### ISSUE TITLE
evmapy on a pi4 buster image 

### ISSUE THREAD

**Issue by pidisaster** [kempniu/evmapy#1]
i tried to install it as good as i can (not a software engineer )
the file structure is /home/pi/evmapy 
and no evmapy in the /usr/bin
no idea how to use root user 
sudo evmapy did not work
the boot load setup has also changed
![afbeelding](https://user-images.githubusercontent.com/61390119/75182008-c8b3bc80-573f-11ea-93ad-bb92b7155a7f.png)

**Comment by kempniu** [comment]
AFAICT, you got input handling working just fine - judging from the `BTN_0` and `BTN_1` lines in the output.  Since you have not stated it explicitly, I *assume* the problem is that evmapy does not *generate* input events that you want.  If so, the problem is likely here:

> no idea how to use root user

I can't help you with that.  You need to refer to your operating system's documentation.  This looks like a good start: https://www.raspberrypi.org/documentation/linux/usage/root.md?

Once you have root access, you can either tweak permissions so that the `pi` user (or some other user account you choose for this purpose) has write access to `/dev/uinput` (better) or run evmapy as `root` (worse).
