### ISSUE TITLE
Getting device permission guide in readme

### ISSUE THREAD

**Issue by mritunjaymusale** [kempniu/evmapy#5]
Can you add [this guide](https://github.com/robinuniverse/Keebie#how-to-set-up) for helping first time installers to get access to their devices without root.

**Comment by kempniu** [comment]
Sorry, but I do not think this is a good idea.  Even if we agreed that setting up non-root input device access is in scope of this project's documentation, the particular guide you suggested is superficial, outright self-doubting (quote: "I suspect that the way I did it was wrong"), and does not describe any way of setting things up permanently (so that the revised permissions survive a system reboot).  This subject is rather OS-specific, so typing `<name-of-your-operating-system> input device permissions` into one's favorite search engine is probably the most sane thing to suggest.
